#!/bin/bash
rowNum=0
colNum=0
loopCo=0
while read row
do	
	echo Loop counter: $loopCo
	if (($rowNum ==  0)); then
		for i in $row
		do
			colNum=`expr $colNum + 1` 
		done 
	fi
	rowNum=`expr $rowNum + 1`
done < $1
echo Row: $rowNum
echo Col: $colNum
