#!/bin/bash
m1=./tempm1
m2=./tempm2

rm -f $m1
rm -f $m2
colNum=1
for j in $(seq 1 $colNum)
do
	echo Loop $j
	cut -f"$j" $2 > $m2
	echo after cut
	sed "${j}q;d" $1 > $m1
	echo end
	cat $m1
	cat $m2
	count=1
	total=0
	while read num
	do
		echo inner loop $count
		num=$(cut -f"$count" $m1)
		total=`expr $total + $(tail -n +"$count" $m2 |head -n 1) \* $num`
		count=`expr $count + 1`
		
	done < $m2
	echo total $j $total	
done
